In [2]:
import pandas as pd
from padelpy import from_smiles

# 1. Define your chemical structures using SMILES strings

smiles_list = [
    "CC(=O)OC1=CC=CC=C1C(=O)O",  # Aspirin
    "CN1C=NC2=C1C(=O)N(C(=O)N2C)C",  # Caffeine
]

print("Calculating descriptors... (This may take a few seconds)")

fingerprints = from_smiles(smiles_list, fingerprints=True, descriptors=False)

# 3. Convert the results into a clean Pandas DataFrame
df = pd.DataFrame(fingerprints)


print("\nCalculation complete! Shape of data:", df.shape)
df.head()

Calculating descriptors... (This may take a few seconds)

Calculation complete! Shape of data: (2, 881)

,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,PubchemFP9,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [4]:
df = pd.read_csv("molecular_fingerprints.csv")
df

,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,PubchemFP9,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [5]:
df.shape

(2, 881)

In [ ]:
import torch.nn as nn

class CNN(nn.Module):

    def init(self, num_classes=3):
        super().init()

        self.features = nn.Sequential(

            nn.Conv2d(3,32,3,padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(32,64,3,padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(64,128,3,padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.AdaptiveAvgPool2d((1,1))
        )

        self.classifier = nn.Sequential(

            nn.Flatten(),

            nn.Linear(128,64),

            nn.ReLU(),

            nn.Dropout(0.5),

            nn.Linear(64,num_classes)
        )

    def forward(self,x):

        x=self.features(x)

        x=self.classifier(x)

        return x